package com.zapominacz.studia.akprojekt;

import com.zapominacz.studia.akprojekt.utils.MnemonicCodeTranslator;
import com.zapominacz.studia.akprojekt.utils.Registers;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

import javax.swing.*;

public class MainWindow extends JFrame implements StatusChangeInterface {



    private RSyntaxTextArea codeTextPane;
    private RSyntaxTextArea asmTextPane;

    private JMenuBar menuBar;
    private JMenu fileMenu;
    private JMenu programMenu;
    private JMenuItem breakMenuItem;
    private JMenuItem continueMenuItem;
    private JMenuItem nextMenuItem;
    private JMenuItem openMenuItem;
    private JMenuItem stopMenuItem;
    private JMenuItem translateMenuItem;
    private JMenuItem runMenuItem;
    private JMenuItem saveAsMenuItem;
    private JMenuItem saveMenuItem;

    private JLabel[] registerLabels;

    private RTextScrollPane asmScrollPane;
    private RTextScrollPane codeScrollPane;
    private JScrollPane regScrollPane;
    private JPanel jPanel1;
    private JComboBox showInSystemComboBox;
    private JLabel showInSystemLabel;
    private JLabel statusLabel;
    private JTabbedPane editorPane;
    private JSplitPane splitPane;

    private UserGuiActionsAdapter guiActionsAdapter;
    private MnemonicCodeTranslator translator;
    private Compiler compiler;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        translator = new MnemonicCodeTranslator();
        guiActionsAdapter = new UserGuiActionsAdapter();
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        statusLabel = new JLabel();
        splitPane = new JSplitPane();
        editorPane = new JTabbedPane();


        asmTextPane = new RSyntaxTextArea(20, 60);
        asmTextPane.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_ASSEMBLER_X86);
        asmTextPane.setCodeFoldingEnabled(true);
        asmScrollPane = new RTextScrollPane(asmTextPane);


        codeTextPane = new RSyntaxTextArea(20, 60);
        codeTextPane.setCodeFoldingEnabled(true);
        codeScrollPane = new RTextScrollPane(codeTextPane);


        regScrollPane = new JScrollPane();
        jPanel1 = new JPanel();

        registerLabels = new JLabel[Registers.REGISTERS];
        for(int i = 0; i < Registers.REGISTERS; i++) {
            String registerName = "R" + Integer.toHexString(i).toUpperCase();
            registerLabels[i] = new JLabel(registerName);
            guiActionsAdapter.connectTextFieldWithRegister(i, new JTextField("0x00000000"));
        }

        showInSystemLabel = new JLabel();
        showInSystemComboBox = new JComboBox();
        menuBar = new JMenuBar();
        fileMenu = new JMenu();
        openMenuItem = new JMenuItem();
        saveAsMenuItem = new JMenuItem();
        saveMenuItem = new JMenuItem();
        programMenu = new JMenu();
        runMenuItem = new JMenuItem();
        translateMenuItem = new JMenuItem();
        nextMenuItem = new JMenuItem();
        breakMenuItem = new JMenuItem();
        stopMenuItem = new JMenuItem();
        continueMenuItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projekt AK");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("mainFrame"); // NOI18N

        statusLabel.setText("Wszystko OK");

        splitPane.setDividerLocation(400);
        splitPane.setDividerSize(1);

        editorPane.addTab("asembler", asmScrollPane);

        editorPane.addTab("kod", codeScrollPane);

        splitPane.setLeftComponent(editorPane);

        showInSystemLabel.setText("Reprezentacja:");

        showInSystemComboBox.setModel(new DefaultComboBoxModel(new String[]{"HEX", "DEC"}));
        showInSystemComboBox.addActionListener(e1 -> guiActionsAdapter.onSystemChanged(showInSystemComboBox));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        GroupLayout.ParallelGroup registerGroup = jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING);
        for(int i = 0; i < Registers.REGISTERS; i++) {
            registerGroup = registerGroup.addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(registerLabels[i])
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(guiActionsAdapter.getRegister(i).getRepresentation(), GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE));
        }
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(registerGroup)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(showInSystemLabel)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(showInSystemComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GroupLayout.SequentialGroup registerVerticalGroup = jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(showInSystemLabel)
                        .addComponent(showInSystemComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE));
        for(int i = 0; i < Registers.REGISTERS; i++) {
            registerVerticalGroup = registerVerticalGroup
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(registerLabels[i])
                            .addComponent(guiActionsAdapter.getRegister(i).getRepresentation(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE));
        }
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(registerVerticalGroup
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        regScrollPane.setViewportView(jPanel1);

        splitPane.setRightComponent(regScrollPane);

        fileMenu.setText("Plik");
        fileMenu.setToolTipText("");
        fileMenu.setActionCommand("Plik");

        openMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(e -> guiActionsAdapter.onOpenFile(asmTextPane, MainWindow.this));
        fileMenu.add(openMenuItem);

        saveAsMenuItem.setText("Zapisz jako...");
        fileMenu.add(saveAsMenuItem);
        saveAsMenuItem.addActionListener(e -> guiActionsAdapter.onSaveAsFile(asmTextPane, MainWindow.this));

        saveMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Zapisz");
        saveMenuItem.setToolTipText("");
        saveMenuItem.setActionCommand("Zapisz");
        saveMenuItem.addActionListener(e -> guiActionsAdapter.onSaveFile(asmTextPane, MainWindow.this));
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        programMenu.setText("Program");
        programMenu.setToolTipText("");

        translateMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        translateMenuItem.setText("Translate");
        translateMenuItem.addActionListener(e -> translator.translateAssemblyCode(asmTextPane, codeTextPane));
        programMenu.add(translateMenuItem);

        runMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        runMenuItem.setText("Uruchom");
        runMenuItem.addActionListener(e -> guiActionsAdapter.onRunProgram(asmTextPane, codeTextPane));
        programMenu.add(runMenuItem);

        nextMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nextMenuItem.setText("Nastêpna linia");
        nextMenuItem.addActionListener(e -> guiActionsAdapter.onNextLine(asmTextPane, codeTextPane));
        programMenu.add(nextMenuItem);

        breakMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        breakMenuItem.setText("Toggle breakpoint");
        breakMenuItem.addActionListener(e -> guiActionsAdapter.onBreakPointToggle(asmTextPane, codeTextPane));
        programMenu.add(breakMenuItem);

        stopMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        stopMenuItem.setText("Zatrzymaj");
        stopMenuItem.addActionListener(e -> guiActionsAdapter.onInterrupt(asmTextPane, codeTextPane));
        programMenu.add(stopMenuItem);

        continueMenuItem.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        continueMenuItem.setText("Kontynuuj");
        continueMenuItem.addActionListener(e -> guiActionsAdapter.onContinue(asmTextPane, codeTextPane));
        programMenu.add(continueMenuItem);

        menuBar.add(programMenu);

        setJMenuBar(menuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(splitPane, GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                                        .addComponent(statusLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(splitPane)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusLabel)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    @Override
    public void changeStatus(String msg) {
        statusLabel.setText(msg);
    }
    // End of variables declaration                   
}
